server:
  port: 8889
#spring:
#  application:
#    name: config-server #应用程序名称
#  cloud:
#    config:
#      server:
#        git:
#          uri:  https://github.com/yzm272/pear.git #git上，配置文件地址
#spring:
#  application:
#    name: config-server #应用程序名称
#  cloud:
#    config:
#      server:
#          git:
#            uri: https://github.com/yzm272/pear.git
##          uri: https://github.com/xuwenjin/config-repo-xwj.git
#          #          username: github 登录账号
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://user:123456@localhost:8080/eureka/,http://localhost:8080/eureka/
#
spring:
  application:
    name: config-server  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yzm272/pear.git
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8080/eureka/,http://localhost:8080/eureka/
#          default-label: master #配置文件分支
#          search-paths: config  #配置文件所在根目录
